export const products = [
  {
    "handle": "prod_0001",
    "name": "Bangkok Shophouses",
    "description": "插畫介紹曼谷老城區建築的歷史文化。",
    "instock_price": 870,
    "book_type": "泰國藝文書籍",
    "image_url_cover": "https://drive.google.com/file/d/16ejqWaDbbY1SBHeGdXejsmwo8VLo1WKu/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1viV7boPHmjoazvMxu6jFjZ_-XYOlfS1A/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰英",
    "ai_notes": "這是一本獻給曼谷經典建築「店屋 (Shophouse)」的畫作集。作者 Louis Sketcher 透過細膩的鉛筆素描、鋼筆畫和水彩，捕捉了這些兼具商業與居住功能的老建築獨特的歷史風貌與文化底蘊。\n\n本書不僅僅是建築的寫生，更是對曼谷舊城區鄰里生活的溫情紀錄。書中以泰英雙語呈現，帶領讀者穿梭於曼谷迷宮般的巷弄，探索從老城中心到昭披耶河對岸的店屋故事。您會看到印度區、華人貿易中心、批發市場以及那些隱藏在尋常巷弄中的精緻建築細節，如窗飾、木雕和陽台上的鐵花窗。對於喜愛城市漫遊、建築美學和想從不同視角體驗曼谷的讀者來說，這是一本值得收藏的靈感之書。\n\n本書特點：\n\n主題： 曼谷店屋建築、街區文化與生活。\n\n形式： 精裝本，全彩印刷，收錄大量手繪插畫。\n\n語言： 泰英雙語。"
  },
  {
    "handle": "prod_0002",
    "name": "Moments in Chiang Mai",
    "description": "插畫介紹清邁美食與建築。",
    "instock_price": 870,
    "book_type": "泰國藝文書籍",
    "image_url_cover": "https://drive.google.com/file/d/1v8UF16dPuECYdYN_qpwPe0WwwB95AGzm/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1HAh6d8-YlL9YQ_UG5P7c2XgFonIziyFT/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰英",
    "ai_notes": "繼《Bangkok Shophouses》之後，作者 Louis Sketcher 將他的畫筆轉向了泰北玫瑰——清邁。這本書同樣以他標誌性的手繪風格，記錄下在清邁的所見所聞與迷人瞬間。\n\n從書名的「Moments (瞬間)」可以看出，本書更側重於捕捉作者在清邁的個人體驗與第一印象。內容涵蓋了清邁獨特的飲食文化、蘭納風格的建築、別具一個的方言以及悠閒清新的自然氛圍。透過作者的畫筆和文字，讀者可以感受到一位旅人對這座城市的深厚情感，從初次到訪的青澀大學生，到帶著畫具和速寫本一次次重遊的藝術家。書中同樣以泰英雙語呈現，讓不同語言的讀者都能一同感受清邁的魅力。\n\n本書特點：\n\n主題： 清邁的旅行印象、建築、文化與自然風光。\n\n形式： 精裝本，以手繪插畫和散記為主。\n\n語言： 泰英雙語。"
  },
  {
    "handle": "prod_0003",
    "name": "365 DAYS OF THAI URBAN MESS ARCHITECTURE",
    "description": "泰國街頭建築物件的設計。\n雖然媽媽說那裡太危險 推薦",
    "instock_price": 445,
    "book_type": "泰國藝文書籍",
    "image_url_cover": "https://drive.google.com/file/d/14MwEA5DNGwmVCp1FzfS4pj1LhECq9lHS/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1B4IIVOctw798rgxwoR88WRuG4ziW46VY/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": "這是一本視角極為獨特的建築與社會觀察書籍。書名中的「Mess Architecture」直譯為「混亂的建築」，而泰文副標題「สถาปัตยกรรมคณะเรี่ยราด」更帶有一種戲謔的意味，巧妙地將「คณะราษฎร (人民黨)」置換為「คณะเรี่ยราด (雜亂無章)」。\n\n作者 Chatchavan Suwansawat 是一位建築師，他將目光從宏偉的紀念碑式建築移開，轉而聚焦於泰國城市中由普通人為了應對日常生活需求而「設計」出來的物件與空間。書中記錄了他在365天裡觀察到的各種城市景象：臨時搭建的攤販、被隨意改造的遮雨棚、奇特的管線佈局等。這些看似混亂、不入流的「設計」，卻真實地反映了都市中不平等的居住環境與泰國特有的在地生活智慧。\n\n本書挑戰了傳統建築學的定義，引導讀者思考什麼才是真正的「建築」，並從這些常被社會忽視的細節中，看見混亂中共存的生命力與獨特的城市紋理。\n\n本書特點：\n\n主題： 泰國都市的「非典型」建築、常民設計與社會觀察。\n\n形式： 收錄大量紀實照片與評論性文字。\n\n核心概念： 透過「混亂」看見真實的都市生活與民間智慧。"
  },
  {
    "handle": "prod_0004",
    "name": "漢泰小辭典",
    "description": "中泰單字口袋書。",
    "instock_price": 215,
    "book_type": "泰語雙語學習書",
    "image_url_cover": "https://drive.google.com/file/d/13RWt_6KjYW2X9EMED-hILdczflCA7XMv/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/18FtoYx8z99VreYiBDRAKbxHk8EqTV3ik/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰中",
    "ai_notes": ""
  },
  {
    "handle": "prod_0005",
    "name": "หนังสือ 1000 คำศัพท์ภาษาจีนสำหรับเด็ก",
    "description": "泰國小朋友學中文的書，看得懂泰文的人也可以讀看看，有精美插畫和各種生活主題。",
    "instock_price": 330,
    "book_type": "泰語雙語學習書",
    "image_url_cover": "https://drive.google.com/file/d/1kCkFGZoqvKY7ic2Y9XCxu_if6mPuyRDK/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1h70fl6GpCfWQuDnxDS7_R2fpbwA0OCDe/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰中",
    "ai_notes": "這是專為泰國兒童設計的中文啟蒙詞彙書，由泰國知名的教育圖書出版社（如 MIS Publishing）發行。\n\n目標讀者： 正在初學中文的泰國兒童。\n\n核心內容： 精選1000個最基礎、最貼近兒童生活的中文詞彙。\n\n主要特點：\n\n主題分類： 內容通常會按照主題分類，例如「身體」、「家庭」、「動物」、「食物」、「交通工具」等，幫助孩子系統性記憶。\n\n圖文並茂： 每一頁都有色彩鮮豔、生動可愛的插圖，用圖像來對應詞彙，加深孩子的記憶。\n\n三語標示： 書中每個詞彙都會包含 中文漢字、拼音 和 泰文翻譯，讓家長或老師能輕鬆引導。\n\n這是一本典型的「寓教於樂」型童書，旨在透過有趣的視覺和聽覺體驗，引發孩子學習中文的興趣。"
  },
  {
    "handle": "prod_0006",
    "name": "50 short stories: only in thailand",
    "description": "這本非常有趣! 推! 50個短故事\n用非常口語的泰文幽默講述泰國生活的事。",
    "instock_price": 450,
    "book_type": "泰語雙語學習書",
    "image_url_cover": "https://drive.google.com/file/d/1itTtmKpQb-r5bfzY-IBIYmHHueYMvayN/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/16gTRmhlWh57af4icWRYlfjY01LiUoIx4/view?usp=drive_link",
    "image_url_2": "https://drive.google.com/file/d/1fLdOz_H1FKlk3GPJrIj3WMHRz3hg04IW/view?usp=drive_link",
    "is_bestseller": true,
    "specification": "泰英",
    "ai_notes": "專門搜羅泰國獨有的奇聞軼事、社會文化現象、網路熱門話題或都市傳說。內容非常接地氣，對於泰國讀者來說既親切又有趣。例如，可能會讀到關於泰國特殊交通狀況、奇特的信仰或是一些讓人會心一笑的本地新聞。"
  },
  {
    "handle": "prod_0007",
    "name": "50 short stories: life lessons inspiring stories",
    "description": "50個短故事同一系列作者新書，以人生議題為主。",
    "instock_price": 433,
    "book_type": "泰語雙語學習書",
    "image_url_cover": "https://drive.google.com/file/d/1GWPOvDYJH8Q3qjHqfVSnB6z2OXs-5ibp/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰英",
    "ai_notes": "彙集了世界各地的寓言、名人勵志小故事、感人肺腑的真實事件或富含哲理的民間傳說。旨在傳遞正面價值觀，例如勇氣、誠實、毅力與愛。讀者在學習英文的同時，也能從中獲得人生的啟發。"
  },
  {
    "handle": "prod_0008",
    "name": "50 short stories: mysteries around the world",
    "description": "50個短故事同一系列作者新書，以神秘故事為主題。",
    "instock_price": 433,
    "book_type": "泰語雙語學習書",
    "image_url_cover": "https://drive.google.com/file/d/1kfZoPBhG0N6bbT_fAhBwIrvP-AZHM6sA/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰英",
    "ai_notes": "內容圍繞著全球著名的未解之謎、神秘事件和超自然現象。例如百慕達三角、不明飛行物(UFO)、尼斯湖水怪、古文明之謎等。這個主題非常能吸引讀者的好奇心，讓學習過程像在看一本科普或冒險故事書一樣引人入勝。"
  },
  {
    "handle": "prod_0009",
    "name": "สัญญานะว่าจะยิ้มให้กับตัวเอง\n約定好，要為自己而笑",
    "description": "Mindy老師推薦!\n溫暖療癒的書籍，泰文密度不高，適合閱讀新手。",
    "instock_price": 390,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1Dtb4zXhbhLAmtHvtSy69HtQcU1xjZld1/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1BcNQIBkE0RxHQZf48mUIl92nw52gMjJr/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰",
    "ai_notes": ""
  },
  {
    "handle": "prod_0010",
    "name": "อย่าลืมหยอดรอยยิ้มใส่กระปุก แล้วพกความสุขใส่กระเป๋า\n別忘了把微笑存進撲滿，然後把幸福裝進口袋",
    "description": "前面這本作者的新書，內容也好閱讀。",
    "instock_price": 390,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1aOWYKXqylTM3dl6rzjR-JREcFdDQ3HSx/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰",
    "ai_notes": ""
  },
  {
    "handle": "prod_0011",
    "name": "quotes to you",
    "description": "Freen去馬爾地夫看的書。",
    "instock_price": 600,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1nWOECysGLqDyhzDKVfHTg33NMxpaU6hU/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1LNOslTuuLi_d9WBqgdcQQLfl6QTDksat/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰",
    "ai_notes": ""
  },
  {
    "handle": "prod_0012",
    "name": "ทุกวันคือของขวัญจากตัวเอง\n每一天，都是自己給的禮物",
    "description": "有366天，每天一頁短篇，適合給想開始練習短文閱讀的泰語學習者。",
    "instock_price": 480,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1gEVIxbOlY52L708okopnatH-LSKZuEB7/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1lPAsRUZYy9H2BDOefaayuGF0peVAJ03G/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰",
    "ai_notes": ""
  },
  {
    "handle": "prod_0013",
    "name": "ถ้าโลกมันแย่ก็แค่คิดแบบคาปิบาร่า\n如果世界很糟，就學水豚思考吧",
    "description": "和capybara一家人換個角度思考生活小煩惱，雖然頁數多，但用詞不難，適合閱讀新手。",
    "instock_price": 610,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1P0qdiNukXCnaP7VOsUb19CCKwhVm4S0f/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1VqMo4ysl13fHn5A0qt0fgFLbVpoSrQ48/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": true,
    "specification": "泰",
    "ai_notes": "這本書的概念非常現代，結合了時下的網路文化。水豚 (Capybara) 在網路上是「情緒穩定、與世無爭」的代名詞，牠們總是一副極度淡定、悠然自得的模樣。\n所以，這本書想傳達的核心是：當你覺得生活一團亂、世界讓你失望時，不妨學學水豚的「淡定哲學」——放鬆下來，接受現實，保持內心平靜，不讓外界的紛擾過度影響自己。這是一種充滿趣味的「鬆弛感」生活提案。"
  },
  {
    "handle": "prod_0014",
    "name": "กว่าผมจะตื่น เธอก็คงไปดูแมวห้องคนอื่นเสียแล้ว\n等我醒來，你就大概去看其他房間裡的貓了",
    "description": "- 透過貓的視角或與貓的互動，反思生活中的哲理\n- 每篇可能只有三到四行，但句子難易度落差大\n- 貓奴可能會喜歡555",
    "instock_price": 425,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/140KyWQ5XSKPS7VI6fxaahlvqq0usdr9X/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1LiXTbL1_3N4iiin7Cy-sqw305zAcxJia/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": ""
  },
  {
    "handle": "prod_0015",
    "name": "（黑貓封面）กว่าผมจะตื่น เธอก็คงไปดูแมวห้องคนอื่นเสียแล้ว\n等我醒來，你就大概去看其他房間裡的貓了",
    "description": "",
    "instock_price": 425,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1EPwITM8mKew3Am4sWj6d8QHtDxI6F40r/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": ""
  },
  {
    "handle": "prod_0016",
    "name": "貓貓書（黑貓）แมวยิ้มง่ายใช่ว่าแตกสลายไม่เป็น บทสนทนาว่าด้วยรอยขีดข่วนของยุคสมัย\n貓咪笑得容易，不代表不會心碎。",
    "description": "",
    "instock_price": 430,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/16Xv7P-16RQ9lGmHaBS-aMSN-sqF1ItKE/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": "這本書的層次更為深刻。作者以「愛笑的貓咪」比喻那些在生活中總是展現開朗、堅強一面的人們，但笑容背後，可能隱藏著不為人知的脆弱與疲憊（「不代表不會心碎」）。書中透過貓咪的視角，觀察和反思現代社會帶給人們的無形壓力、焦慮與倦怠（「時代的刮痕」）。內容觸及了資本主義下的比較文化、對成功的定義、以及在快節奏生活中如何尋找喘息空間。這是一本非常能引起年輕世代共鳴的療癒之書，提醒讀者正視內心的傷痕，並學習像貓一樣，溫柔地對待自己。"
  },
  {
    "handle": "prod_0017",
    "name": "貓貓書（黑橘貓）แมวตื่นสายมักจะโดนแมวตื่นเช้าคิดถึงก่อนเสมอ \n晚起的貓，通常總是被早起的貓提早想念。",
    "description": "",
    "instock_price": 430,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1ehptgRwiX3_70PzrDc2JJrBGaZwt-QEg/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/170tdhe2n65JtzHpejN3COQdxUH0i28no/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": "這本書的副標題是「關於貓、咖啡和你的對話」。內容圍繞著日常生活中的愜意片刻，探討人與人之間不對等的關懷與思念。書名比喻在一段關係中，總有一方是比較主動、先付出關心的「早起的貓」，而另一方則是比較被動、悠閒的「晚起的貓」。儘管步調不同，但這份「先想到你」的心情，構成了關係中最溫暖的底色。書中充滿了對話體的短文，描寫了希望找到一個像「家」一樣安心的關係，可以在對方面前卸下所有防備，做最真實的自己。"
  },
  {
    "handle": "prod_0018",
    "name": "貓貓書（橘貓）แมวน่ารักมีเยอะแต่เชื่อเถอะแมวส้มดีที่สุดแล้ว \n可愛的貓有很多，但相信我吧! 橘貓最好了",
    "description": "",
    "instock_price": 420,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1Sh8Z_LZx9zIfcLvp36rdloswCn1XuVXt/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": "這是作者「貓咪系列」的最新作品，這次的主角是「橘貓」。在網路文化中，橘貓常被認為是特別淘氣、貪吃又可愛的存在。這本書透過與橘貓的互動，探討「偏愛」這個主題。即使世界上有許多「可愛的貓」（美好的選項），但總有那麼一個對你而言是「最棒的」（獨一無二的存在）。書的副標題是「關於那些不會只搔搔你下巴就轉身離開的人」，暗示了這本書也在探討如何尋找並珍惜一段穩定、不會輕易離去的關係。內容延續了作者一貫的風格，以幽默、溫暖的筆觸，描寫人貓之間（以及人與人之間）的深刻連結。"
  },
  {
    "handle": "prod_0019",
    "name": "หลงรักแมวนักเดินทาง\n愛上旅行貓",
    "description": "以貓去日本各個地方旅行為主題，喜歡日本文化的朋友，可以透過這本學習日本文的美食旅遊泰文。",
    "instock_price": 330,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1QYJi1i3vA9yZTaO7G3Hc1IUQCkfC-klN/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1ZJ2S6XO0vmLG9qEjUNqE9NYFAucUWymf/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": ""
  },
  {
    "handle": "prod_0020",
    "name": "แล้วทำไมต้องใช้ชีวิตให้มันยาก\n為什麼要把人生搞得這麼難。",
    "description": "這系列的書有藝術字和一般字體參雜",
    "instock_price": 320,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/1BI3wPzmVH430cwKIS4ZxbjCSyIePvfXr/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": "這本書的作者「คิดมาก (Kid-Mak)」是泰國知名的網路作家和思想家，以其精煉、直擊人心的文字而聞名。書名本身就是一個對讀者的提問，挑戰我們去思考：生活中遇到的許多困難和壓力，有多少是外界強加的，又有多少是我們自己選擇的？\n全書透過一篇篇短文，探討現代人常有的焦慮，例如：過度在乎他人眼光、追求不必要的完美、被社群媒體綁架、以及不斷內耗的「想太多」心態。它引導讀者學習簡化生活，放下不必要的執著，並從複雜的思緒中走出來，找到更輕鬆、更忠於自我的生活方式。"
  },
  {
    "handle": "prod_0021",
    "name": "ถ้าปัญหามันแก้ไม่ได้ ก็แค่คิดแบบแมว \n如果問題解決不了，就試著用貓貓的方式來思考。",
    "description": "",
    "instock_price": 320,
    "book_type": "泰語短篇書籍",
    "image_url_cover": "https://drive.google.com/file/d/17GM8-3wathORrJsTpMhHe55wk0m50iaN/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1FFWlrn4-nWrgIgshEFlCHWnRMtlRH147/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": "這本書專注於將「貓咪哲學」應用在處理問題上。它提出，當我們面對一個棘手的、似乎無法解決的難題時，與其鑽牛角尖，不如學學貓咪：暫時走開、去睡一覺、把注意力轉移到其他地方。有時候，放下執著，問題的答案反而會自己浮現，或者你會發現，那個問題根本沒有那麼重要。這是一本教你如何「策略性放棄」和「轉念」的書。"
  },
  {
    "handle": "prod_0022",
    "name": "ชีวิตดีขึ้นทันทีแค่คิดแบบแมว\n只要像貓一樣思考，生活立刻變好。",
    "description": "作者新作品",
    "instock_price": 340,
    "book_type": "",
    "image_url_cover": "https://drive.google.com/file/d/1xO-tfxGPDqTb1J6smfspXxrk16l_uDrT/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "泰",
    "ai_notes": "這本書則是將「貓咪哲學」擴展到生活的各個層面，像一本更全面的生活風格指南。它涵蓋了工作、人際關係、自我照顧等多個方面，教導讀者如何運用貓咪的智慧來提升整體生活品質。例如：如何像貓一樣優雅地獨處、如何建立舒適的人際距離、如何在混亂中找到屬於自己的安靜角落。它向讀者展示，只要轉變思維模式，就能立即從日常的煩惱中解脫，讓生活變得更美好。"
  },
  {
    "handle": "prod_0023",
    "name": "泰國旅遊筆記本",
    "description": "",
    "instock_price": 260,
    "book_type": "文化小物",
    "image_url_cover": "https://drive.google.com/file/d/1OT7HKWnOPme3ByhUFzaqACHdCVrCAMPZ/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1r-brETgic3CFJFlPf2X-noWATUQUFAqM/view?usp=drive_link",
    "image_url_2": "https://drive.google.com/file/d/1WWYq0zTUaRgJlLFXKp9eK5HjxCPtmrCV/view?usp=drive_link",
    "is_bestseller": true,
    "specification": "",
    "ai_notes": ""
  },
  {
    "handle": "prod_0024",
    "name": "泰國地圖磁性板",
    "description": "",
    "instock_price": 620,
    "book_type": "文化小物",
    "image_url_cover": "https://drive.google.com/file/d/1WwSRJro0Uu7xRTPXZYMn89wJIJedq8zX/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "20*30cm",
    "ai_notes": ""
  },
  {
    "handle": "prod_0025",
    "name": "泰國刮刮樂地圖",
    "description": "",
    "instock_price": 625,
    "book_type": "文化小物",
    "image_url_cover": "https://drive.google.com/file/d/1eqiyNZcgJEHYKzwpOWl1A_dO-b8yNiA6/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "",
    "ai_notes": ""
  },
  {
    "handle": "prod_0026",
    "name": "微型泰式料理冬陰功款",
    "description": "",
    "instock_price": 90,
    "book_type": "文化小物",
    "image_url_cover": "https://drive.google.com/file/d/1EXoXOcVL1BDaVr3eI0oF7iGLB4qt7M4g/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "含鑰匙圈",
    "ai_notes": ""
  },
  {
    "handle": "prod_0027",
    "name": "蛇牌涼感噴霧",
    "description": "",
    "instock_price": 250,
    "book_type": "文化小物",
    "image_url_cover": "https://drive.google.com/file/d/1ENbCLhWEYcmtT9m0leCHrC4XqsXHJdWl/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "原味/薰衣草",
    "ai_notes": ""
  },
  {
    "handle": "prod_0028",
    "name": "合艾炸雞飯短袖",
    "description": "包裝會是包成合艾特色糯米炸雞飯的方式，還以為在吃糯米炸雞飯!",
    "instock_price": 640,
    "book_type": "文化服飾",
    "image_url_cover": "https://drive.google.com/file/d/1i12vhTugUY3LpTCXk10OhAeF8SHLMtGX/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1EDSNGOnyQcPsR9s0QURoE1JZdaGgg5HR/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "FreeSize/XL",
    "ai_notes": ""
  },
  {
    "handle": "prod_0029",
    "name": "合艾炸雞飯短褲",
    "description": "",
    "instock_price": 540,
    "book_type": "文化服飾",
    "image_url_cover": "https://drive.google.com/file/d/11hZcV_Z8NcOrSPpV9r1crlkoetYXljlo/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "FreeSize",
    "ai_notes": ""
  },
  {
    "handle": "prod_0030",
    "name": "普吉島褲",
    "description": "訂購的店家每賣出一件就會捐9泰銖給Baan Ar-Jor Foundation 基金會，資助普吉島當地貧困兒童",
    "instock_price": 350,
    "book_type": "文化服飾",
    "image_url_cover": "https://drive.google.com/file/d/1hJZOnwfDIcKfpDj-magxDzbt791dZU-O/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "FreeSize",
    "ai_notes": ""
  },
  {
    "handle": "prod_0031",
    "name": "柯叻府喵喵褲",
    "description": "",
    "instock_price": 360,
    "book_type": "文化服飾",
    "image_url_cover": "https://drive.google.com/file/d/1cCjihLNbhB9Wn42Qwakenikm1g__jiDt/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "FreeSize",
    "ai_notes": ""
  },
  {
    "handle": "prod_0032",
    "name": "這是什麼巨蜥衣服",
    "description": "",
    "instock_price": 450,
    "book_type": "新貨",
    "image_url_cover": "https://drive.google.com/file/d/1W2GAlMOf1TFr1VIc5nw6fY87N5XZf7Hy/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "M/L",
    "ai_notes": ""
  },
  {
    "handle": "prod_0033",
    "name": "PEK鼻通",
    "description": "",
    "instock_price": 100,
    "book_type": "新貨",
    "image_url_cover": "https://drive.google.com/file/d/1-ewRnFy9Q3blrSysKehxbkQsYv_IWQQh/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "檸檬/西瓜",
    "ai_notes": ""
  },
  {
    "handle": "prod_0034",
    "name": "佛祖求救口哨",
    "description": "",
    "instock_price": 300,
    "book_type": "新貨",
    "image_url_cover": "https://drive.google.com/file/d/11xFtCILwZTWxibGo1RSzYFOLqG67y5U9/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1oAMZzKdvjEGHgyuYlyQPw2tX3FN5Rs2x/view?usp=drive_link",
    "image_url_2": "https://drive.google.com/file/d/1fmh43kR-xfFqhdcErNO6zYKJcqJEN9iU/view?usp=drive_link",
    "is_bestseller": false,
    "specification": "奶油色/粉色/橘色/紅色",
    "ai_notes": ""
  }
  ,
  {
    "handle": "prod_0035",
    "name": "泰國好運錢包袋",
    "description": "",
    "instock_price": 60,
    "book_type": "搗搗選物",
    "image_url_cover": "https://drive.google.com/file/d/1z5-3aSV4y0cWB7KvoNdQpePEqPdSRD_m/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1TEpkZwCCtIUVS93pFc68q8HFt0d7pVFC/view?usp=drive_link",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "藍/白/黃/綠",
    "ai_notes": ""
  }
  ,
  {
    "handle": "prod_0036",
    "name": "樂透手鍊",
    "description": "",
    "instock_price": 100,
    "book_type": "搗搗選物",
    "image_url_cover": "https://drive.google.com/file/d/1Nxf4dvq4NacmYQCefgZjpz2avCWHfGLx/view?usp=drive_link",
    "image_url_1": "https://drive.google.com/file/d/1Nxf4dvq4NacmYQCefgZjpz2avCWHfGLx/view?usp=drive_link",
    "image_url_2": "https://drive.google.com/file/d/15TVVxaVO3qDxRVoanrUBZ9G_Ia4ZyCio/view?usp=drive_link",
    "is_bestseller": false,
    "specification": "米白/桃紫",
    "ai_notes": ""
  }
  ,
  {
    "handle": "prod_0037",
    "name": "鞋扣組",
    "description": "",
    "instock_price": 200,
    "book_type": "搗搗選物",
    "image_url_cover": "https://drive.google.com/file/d/1EV-2iSLD9X6tFsGw2kXyu6YDnc3-22CV/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "",
    "ai_notes": ""
  }
  ,
  {
    "handle": "prod_0038",
    "name": "別針",
    "description": "",
    "instock_price": 80,
    "book_type": "搗搗選物",
    "image_url_cover": "https://drive.google.com/file/d/1Cw5fJH2H3FFbjqu8kg9mdqnu_lAc6RHW/view?usp=drive_link",
    "image_url_1": "",
    "image_url_2": "",
    "is_bestseller": false,
    "specification": "巨人/國旗/大象/泰拳褲",
    "ai_notes": ""
  }
];
